# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'Catalog' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Catalog
  pod 'gRPC-ProtoRPC'
  pod '!ProtoCompiler-gRPCPlugin'
end
